import {test,expect} from '@playwright/test';
async function seed(page){await page.goto('/index.html');await page.evaluate(async()=>{localStorage.clear();await window.APP_DATA.clearAllData();const date=value=>{const d=new Date();d.setDate(d.getDate()+value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};const ex=(id,name,muscle,sets,bodyweight=false)=>({id,exerciseId:id,name,muscle,bodyweight,sets});const sessions=[{id:'latest',date:date(-1),status:'finalizado',exercises:[ex('press-banca','Press de banca','Pecho',[{id:'a',reps:8,weight:60},{id:'b',reps:9,weight:60},{id:'b2',reps:9,weight:60}]),ex('press-inclinado','Press inclinado','Pecho',[{id:'c',reps:8,weight:40}]),ex('dominadas','Dominadas','Espalda',[{id:'d',reps:10,weight:0,isBodyweight:true}],true)]},{id:'older',date:date(-8),status:'finalizado',exercises:[ex('press-banca','Press de banca','Pecho',[{id:'e',reps:8,weight:60},{id:'e2',reps:8,weight:60},{id:'e3',reps:8,weight:60}]),ex('dominadas','Dominadas','Espalda',[{id:'f',reps:8,weight:0,isBodyweight:true}],true)]}];window.APP_REPOSITORIES.workout.set(window.WORKOUT_FEATURES.keys.workoutSessions,sessions);await window.APP_DATA.flush();});}

test('Ejercicio muestra mejor carga, serie, e1RM, historial y recomendacion',async({page})=>{await seed(page);await page.goto('/index.html?module=progress&view=gym&progressScope=exercise&exerciseId=press-banca');await expect(page.locator('[data-progress-gym-panel="exercise"]')).toBeVisible();await expect(page.locator('#progressExerciseSelect')).toHaveValue('press-banca');await expect(page.locator('#progressExerciseSummary')).toContainText('60 kg');await expect(page.locator('#progressExerciseSummary')).toContainText('78 kg');await expect(page.locator('#progressExerciseHistory')).toContainText('60 kg × 9');await expect(page.locator('#progressRecommendationText')).toContainText('repetición adicional');await expect(page.locator('#progressRecommendationMeta')).toContainText('3 series');await expect(page.locator('#progressRecommendationMeta')).toContainText('sesiones');await expect(page.locator('#progressExerciseChartSummary')).toContainText('Press de banca');});

test('Doble progresión exige dos sesiones completas y RIR objetivo',async({page})=>{await seed(page);await page.evaluate(async()=>{const key=window.WORKOUT_FEATURES.keys.workoutSessions,date=value=>{const d=new Date();d.setDate(d.getDate()+value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;},sets=prefix=>[1,2,3].map(index=>({id:`${prefix}-${index}`,reps:12,weight:60,rir:2,setType:'working'}));window.APP_REPOSITORIES.workout.set(key,[{id:'latest-load',date:date(-1),exercises:[{id:'press-banca',exerciseId:'press-banca',name:'Press de banca',muscle:'Pecho',sets:sets('a')}]},{id:'older-load',date:date(-8),exercises:[{id:'press-banca',exerciseId:'press-banca',name:'Press de banca',muscle:'Pecho',sets:sets('b')}]}]);const plan=window.WORKOUT_FEATURES.getWeeklyWorkoutPlan();Object.values(plan).forEach(day=>(day.exercises||[]).forEach(exercise=>{if(exercise.exerciseId==='press-banca')Object.assign(exercise,{targetSets:3,repsMin:8,repsMax:12,targetRirMin:1,targetRirMax:3,progressionMode:'doubleProgression',incrementKg:2.5});}));window.APP_REPOSITORIES.workout.set(window.WORKOUT_FEATURES.keys.weeklyWorkoutPlan,plan);await window.APP_DATA.flush();});await page.goto('/index.html?module=progress&view=gym&progressScope=exercise&exerciseId=press-banca');await expect(page.locator('#progressRecommendationText')).toContainText('incremento mínimo');await expect(page.locator('#progressRecommendationMeta')).toContainText('Confianza alta');await expect(page.locator('#progressRecommendationMeta')).toContainText('62.5 kg');});

test('Variantes permanecen separadas y Atrás restaura el ejercicio',async({page})=>{await seed(page);await page.goto('/index.html?module=progress&view=gym&progressScope=exercise&exerciseId=press-banca');await page.locator('#progressExerciseSelect').selectOption('press-inclinado');await expect(page).toHaveURL(/exerciseId=press-inclinado/);await expect(page.locator('#progressExerciseSummary')).toContainText('40 kg');await page.goBack();await expect(page.locator('#progressExerciseSelect')).toHaveValue('press-banca');await expect(page.locator('#progressExerciseSummary')).toContainText('60 kg');});

test('Peso corporal y records no presentan cero kilos como fuerza',async({page})=>{await seed(page);await page.goto('/index.html?module=progress&view=gym&progressScope=exercise&exerciseId=dominadas');await expect(page.locator('#progressExerciseSummary')).toContainText('Sin lastre');await expect(page.locator('#progressExerciseSummary')).toContainText('10 reps');await expect(page.locator('#progressExerciseSummary')).not.toContainText('0 kg');await page.locator('[data-progress-gym-scope="records"]').click();await expect(page.locator('#progressRecordsList')).toContainText('Press de banca');const bodyweightRecords=page.locator('.progressRecordRow').filter({hasText:'Dominadas'});await expect(bodyweightRecords).toContainText('10 reps');await expect(bodyweightRecords).not.toContainText('kg');});
