(function(global){
  'use strict';
  let resolver=null,previousFocus=null,fields=[];
  function nodes(){return{backdrop:document.getElementById('appFormDialogBackdrop'),form:document.getElementById('appFormDialogForm'),title:document.getElementById('appFormDialogTitle'),message:document.getElementById('appFormDialogMessage'),fields:document.getElementById('appFormDialogFields'),submit:document.getElementById('appFormDialogSubmit'),cancel:document.getElementById('appFormDialogCancel'),close:document.getElementById('appFormDialogClose')};}
  function finish(value){if(!resolver)return;const n=nodes(),resolve=resolver,focus=previousFocus;resolver=null;previousFocus=null;fields=[];n.backdrop.classList.add('hidden');n.backdrop.setAttribute('aria-hidden','true');n.form.reset();n.fields.replaceChildren();requestAnimationFrame(()=>focus?.focus?.());resolve(value);}
  function inputFor(field){
    const input=field.options?document.createElement('select'):document.createElement(field.multiline?'textarea':'input');
    input.id=`appFormField-${field.name}`;input.name=field.name;
    if(!field.options){input.type=field.type||'text';if(field.inputmode)input.inputMode=field.inputmode;if(field.placeholder)input.placeholder=field.placeholder;if(field.min!==undefined)input.min=field.min;if(field.max!==undefined)input.max=field.max;if(field.step!==undefined)input.step=field.step;}
    else field.options.forEach(option=>{const node=document.createElement('option'),item=typeof option==='object'?option:{value:option,label:option};node.value=String(item.value);node.textContent=String(item.label);input.append(node);});
    input.value=String(field.value??'');input.required=!!field.required;return input;
  }
  function renderFields(container){fields.forEach(field=>{const wrapper=document.createElement('div'),label=document.createElement('label'),input=inputFor(field);wrapper.className='field';label.htmlFor=input.id;label.textContent=field.label||field.name;wrapper.append(label,input);if(field.hint){const hint=document.createElement('span');hint.className='muted small';hint.textContent=field.hint;wrapper.append(hint);}container.append(wrapper);});}
  function values(){const form=nodes().form;return Object.fromEntries(fields.map(field=>[field.name,form.elements.namedItem(field.name)?.value??'']));}
  function validate(){const result=values();for(const field of fields){const input=nodes().form.elements.namedItem(field.name),value=result[field.name];window.APP_INLINE_VALIDATION?.clear?.(input);let message='';if(field.required&&!String(value).trim())message=field.requiredMessage||`Completá ${field.label||field.name}.`;else if(typeof field.validate==='function')message=field.validate(value,result)||'';if(message){window.APP_INLINE_VALIDATION?.show?.(input,message);return null;}}return result;}
  function ask({title='Editar',message='',submitLabel='Guardar',cancelLabel='Cancelar',danger=false,fieldList=[]}={}){if(resolver)finish(null);const n=nodes();previousFocus=document.activeElement&&document.activeElement!==document.body?document.activeElement:null;fields=fieldList.filter(field=>field?.name);n.title.textContent=title;n.message.textContent=message;n.message.classList.toggle('hidden',!message);n.submit.textContent=submitLabel;n.submit.classList.toggle('danger',danger);n.submit.classList.toggle('good',!danger);n.cancel.textContent=cancelLabel;n.fields.replaceChildren();renderFields(n.fields);n.backdrop.classList.remove('hidden');n.backdrop.setAttribute('aria-hidden','false');requestAnimationFrame(()=>n.form.elements.namedItem(fields[0]?.name)?.focus());return new Promise(resolve=>{resolver=resolve;});}
  function trap(event){if(!resolver)return;if(event.key==='Escape'){event.preventDefault();finish(null);return;}if(event.key!=='Tab')return;const n=nodes(),focusable=[n.close,...n.fields.querySelectorAll('input,select,textarea,button'),n.cancel,n.submit].filter(item=>!item.hidden&&!item.disabled),index=focusable.indexOf(document.activeElement),next=event.shiftKey?(index<=0?focusable.length-1:index-1):(index===focusable.length-1?0:index+1);event.preventDefault();focusable[next].focus();}
  document.addEventListener('DOMContentLoaded',()=>{const n=nodes();n.form?.addEventListener('submit',event=>{event.preventDefault();const result=validate();if(result)finish(result);});n.cancel?.addEventListener('click',()=>finish(null));n.close?.addEventListener('click',()=>finish(null));n.backdrop?.addEventListener('click',event=>{if(event.target===n.backdrop)finish(null);});document.addEventListener('keydown',trap,true);},{once:true});
  global.APP_FORM_DIALOG=Object.freeze({ask,cancel:()=>finish(null),isOpen:()=>!!resolver});
})(window);
