name: Validar aplicacion

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  quality:
    name: Quality gate beta
    uses: ./.github/workflows/quality-gate.yml
    with:
      channel: beta
    secrets: inherit
